style: use posix-compliant style for all scripts
- fix all lint issues detected by shellcheck
- replace script indentation spaces with tabs
  - while i hate this, it `just works` with heredocs
- remove use of locals, which are not posix-compliant
- quote all variable usage
- replace echo (which is inconsistent) with printf
- move colors to `set-colors` eval script
  - use `tput` for color coding and formatting
  - add functions and aliases for printing:
    - print-notice
    - print-success
    - print-warn
    - print-fail

diff --git a/src/sh/scripts/update-prompt b/src/sh/scripts/update-prompt
--- a/src/sh/scripts/update-prompt
+++ b/src/sh/scripts/update-prompt
@@ -1,95 +1,92 @@
-#!/usr/bin/env sh
+#! /usr/bin/env sh
 
 set -e
 
 __am_prompt_update()
 {
-    local CLR_FAIL=${CLR_FAIL:-"\033[1;31m"}        # BRIGHT RED
-    local CLR_SUCCESS=${CLR_SUCCESS:-"\033[1;32m"}  # BRIGHT GREEN
-    local CLR_WARN=${CLR_WARN:-"\033[1;33m"}        # BRIGHT YELLOW
-    local CLR_CLEAR=${CLR_CLEAR:-"\033[0m"}         # DEFAULT COLOR
+	GITHUB_TOKEN=${GITHUB_TOKEN:-}
+	PROMPT_TOKEN=${PROMPT_TOKEN:-}
+	PROMPT_TOKEN=${PROMPT_TOKEN:-$GITHUB_TOKEN}
+	PROMPT_CURL_OPT=${PROMPT_CURL_OPT:-'-s'}
+	PROMPT_COMMIT_REF=${PROMPT_COMMIT_REF:-"master"}
+	PROMPT_SHELL=${PROMPT_SHELL:-"bash"}
+	PROMPT_DRY_RUN=${PROMPT_DRY_RUN:-}
 
-    local GITHUB_TOKEN=${GITHUB_TOKEN:-}
-    local PROMPT_TOKEN=${PROMPT_TOKEN:-}
-    local PROMPT_TOKEN=${PROMPT_TOKEN:-$GITHUB_TOKEN}
-    local PROMPT_CURL_OPT=${PROMPT_CURL_OPT:-'-s'}
-    local PROMPT_COMMIT_REF=${PROMPT_COMMIT_REF:-"master"}
-    local PROMPT_SHELL=${PROMPT_SHELL:-"bash"}
-    local PROMPT_DRY_RUN=${PROMPT_DRY_RUN:-}
+	while :; do
+		case $1 in
+			-t|--token)
+				PROMPT_TOKEN=$2
+				shift
+				;;
+			-v|--version)
+				PROMPT_COMMIT_REF=$2
+				shift
+				;;
+			-dr|--dry-run)
+				PROMPT_DRY_RUN=1
+				;;
+			-f|--force)
+				rm -rf "$HOME/.am/prompt/.sha" 1>/dev/null 2>&1
+				;;
+			--debug)
+				set -x
+				;;
+			?*)
+				PROMPT_SHELL=$1
+				;;
+			*)
+				break
+				;;
+		esac
+		shift
+	done
 
-    while :; do
-        case $1 in
-            -t|--token)
-                PROMPT_TOKEN=$2
-                shift
-                ;;
-            -v|--version)
-                PROMPT_COMMIT_REF=$2
-                shift
-                ;;
-            -dr|--dry-run)
-                PROMPT_DRY_RUN=1
-                ;;
-            -f|--force)
-                rm -rf "$HOME/.am/prompt/.sha" 1>/dev/null 2>&1
-                ;;
-            --debug)
-                set -x
-                ;;
-            ?*)
-                PROMPT_SHELL=$1
-                ;;
-            *)
-                break
-                ;;
-        esac
-        shift
-    done
+	if [ -n "${PROMPT_TOKEN:-}" ]; then
+		PROMPT_CURL_OPT="$PROMPT_CURL_OPT -H 'Authorization: token $PROMPT_TOKEN'"
+	fi
 
-    if [ ! -z "${PROMPT_TOKEN:-}" ]; then
-        PROMPT_CURL_OPT='$PROMPT_CURL_OPT -H "Authorization: token $PROMPT_TOKEN"'
-    fi
+	PROMPT_SHA_URI="https://api.github.com/repos/automotiveMastermind/prompt/commits/$PROMPT_COMMIT_REF"
+	PROMPT_SHA=$(curl "$PROMPT_CURL_OPT" "$PROMPT_SHA_URI" | grep sha | head -n 1 | sed 's#.*\:.*"\(.*\).*",#\1#')
 
-    local PROMPT_SHA_URI="https://api.github.com/repos/automotiveMastermind/prompt/commits/$PROMPT_COMMIT_REF"
-    local PROMPT_SHA=$(curl $PROMPT_CURL_OPT $PROMPT_SHA_URI | grep sha | head -n 1 | sed 's#.*\:.*"\(.*\).*",#\1#')
+	# detect if sha could be located
+	if [ -z "${PROMPT_SHA:-}" ]; then
+		print-fail "prompt: cannot retrieve SHA of latest version. Are you connected to the internet?"
+		return 1
+	fi
 
-    # detect if sha could be located
-    if [ -z ${PROMPT_SHA:-} ]; then
-        echo "${CLR_FAIL}prompt: cannot retrieve SHA of latest version. Are you connected to the internet?${CLR_CLEAR}"
-        return 1
-    fi
+	PROMPT_SHA_PATH=$HOME/.am/prompt/.sha
 
-    local PROMPT_SHA_PATH=$HOME/.am/prompt/.sha
+	# detect if sha file exists
+	if [ -f "$PROMPT_SHA_PATH" ]; then
 
-    # detect if sha file exists
-    if [ -f "$PROMPT_SHA_PATH" ]; then
+		# get the value of the sha file
+		PROMPT_CURRENT_SHA=$(cat "$PROMPT_SHA_PATH")
 
-        # get the value of the sha file
-        PROMPT_CURRENT_SHA=$(cat "$PROMPT_SHA_PATH")
+		# print latest version already installed
+		if [ "${PROMPT_SHA}" = "${PROMPT_CURRENT_SHA}" ]; then
+			print-success \
+				"prompt: latest version already installed:" \
+				"- run update-prompt with the --force flag to reinstall"
+			return 0
+		fi
+	fi
 
-        # print latest version already installed
-        if [ "${PROMPT_SHA}" = "${PROMPT_CURRENT_SHA}" ]; then
-            echo "${CLR_SUCCESS}prompt: latest version already installed: ${PROMPT_SHA}"
-            echo "  - run update-prompt with the --force flag to reinstall ${CLR_CLEAR}"
-            return 0
-        fi
-    fi
+	if [ -n "${PROMPT_DRY_RUN:-}" ]; then
+		print-warn \
+			"prompt: a new version of prompt is available: ${PROMPT_SHA}" \
+			"- run the update-prompt command line tool to upgrade"
+		return 0
+	fi
 
-    if [ ! -z "${PROMPT_DRY_RUN:-}" ]; then
-        echo "${CLR_WARN}prompt: a new version of prompt is available: ${PROMPT_SHA}"
-        echo "  - run the update-prompt command line tool to upgrade${CLR_CLEAR}"
-        return 0
-    fi
+	PROMPT_INSTALL_URI="https://github.com/automotiveMastermind/prompt/archive/$PROMPT_COMMIT_REF.tar.gz"
+	PROMPT_INSTALL_TEMP=$(mktemp -d)
 
-    local PROMPT_INSTALL_URI="https://github.com/automotiveMastermind/prompt/archive/$PROMPT_COMMIT_REF.tar.gz"
-    local PROMPT_INSTALL_TEMP=$(mktemp -d)
+	curl -skLo "$PROMPT_INSTALL_TEMP/prompt.tgz" "$PROMPT_INSTALL_URI"
+	tar -xzf "$PROMPT_INSTALL_TEMP/prompt.tgz" --strip-components=1 --directory="$PROMPT_INSTALL_TEMP"
 
-    curl -skLo $PROMPT_INSTALL_TEMP/prompt.tgz $PROMPT_INSTALL_URI
-    tar -xzf $PROMPT_INSTALL_TEMP/prompt.tgz --strip-components=1 --directory=$PROMPT_INSTALL_TEMP
-
-    . "$PROMPT_INSTALL_TEMP/install.sh" $PROMPT_SHELL $PROMPT_INSTALL_TEMP
+	"$PROMPT_INSTALL_TEMP/install.sh" "$PROMPT_SHELL" "$PROMPT_INSTALL_TEMP"
 }
 
-trap 'echo; echo; echo "${CLR_WARN}prompt: terminating update...${CLR_CLEAR}"; exit 1;' INT
+trap 'print-warn "prompt: terminating update..."; exit 1;' INT
 
-__am_prompt_update $@
+__am_prompt_update "$@"
diff --git a/src/sh/scripts/use-shell b/src/sh/scripts/use-shell
--- a/src/sh/scripts/use-shell
+++ b/src/sh/scripts/use-shell
@@ -2,82 +2,86 @@
 
 __am_prompt_use_shell() {
 
-    local PROMPT_SHELL=$1
-    ECHO=${ECHO:-"echo"}
+	PROMPT_SHELL=${PROMPT_SHELL:-1}
 
-    if [ -z "${PROMPT_SHELL:-}" ]; then
-        $ECHO "${CLR_FAIL}You must specify a shell to use, either bash or zsh.${CLR_CLEAR}"
-        return 1
-    fi
+	if [ -z "${PROMPT_SHELL:-}" ]; then
+		print-fail "prompt: uou must specify a shell to use, either bash or zsh"
+		return 1
+	fi
 
-    if [ -f /opt/homebrew/bin/brew ]; then
-        local LOCAL_PREFIX=$(/opt/homebrew/bin/brew --prefix)
-    elif command -v brew 1>/dev/null 2>&1; then
-        local LOCAL_PREFIX=$(brew --prefix)
-    elif [ -d $LOCALAPPDATA/git ]; then
-        local LOCAL_PREFIX=$(echo "/$LOCALAPPDATA/git" | sed -e 's/\\/\//g' -e 's/://')
-    else
-        local LOCAL_PREFIX=/usr/local
-    fi
+	if [ -f /opt/homebrew/bin/brew ]; then
+		LOCAL_PREFIX=$(/opt/homebrew/bin/brew --prefix)
+	elif command -v brew 1>/dev/null 2>&1; then
+		LOCAL_PREFIX=$(brew --prefix)
+	elif [ -d "$LOCALAPPDATA/git" ]; then
+		LOCAL_PREFIX=$(printf "%s" "/$LOCALAPPDATA/git" | sed -e 's/\\/\//g' -e 's/://')
+	else
+		LOCAL_PREFIX=/usr/local
+	fi
 
-    local PROMPT_SHELL_PATH="$LOCAL_PREFIX/bin/$PROMPT_SHELL"
-    local INSTALL_PATH="$AM_PROMPT/$PROMPT_SHELL/install"
+	PROMPT_SHELL_PATH="$LOCAL_PREFIX/bin/$PROMPT_SHELL"
+	INSTALL_PATH="$AM_PROMPT/$PROMPT_SHELL/install"
 
-    if [ -f /etc/os-release ]; then
-        . /etc/os-release
-        local UNAMES="$ID $ID_LIKE"
-    else
-        local UNAMES=$(uname | tr '[:upper:]' '[:lower:]')
-    fi
+	if [ -f /etc/os-release ]; then
+		. /etc/os-release
+		UNAMES="$ID ${ID_LIKE:-unknown} linux"
+	else
+		UNAMES=$(uname | tr '[:upper:]' '[:lower:]')
+	fi
 
-    local UNAME=
-    until [ "$UNAME" = "$UNAMES" ]; do
-        local UNAME=${UNAMES%%' '*}
-        local UNAMES=${UNAMES#*' '}
+	UNAME=
+	until [ "$UNAME" = "$UNAMES" ]; do
+		UNAME=${UNAMES%%' '*}
+		UNAMES=${UNAMES#*' '}
 
-        local UNAME_PATH="$INSTALL_PATH/$UNAME.sh"
+		UNAME_PATH="$INSTALL_PATH/$UNAME.sh"
 
-        if [ ! -f "$UNAME_PATH" ]; then
-            continue
-        fi
-    done
+		if [ ! -f "$UNAME_PATH" ]; then
+			continue
+		fi
+	done
 
-    if [ ! -f "$UNAME_PATH" ]; then
-      $ECHO "${CLR_WARN}prompt: shell cannot be installed on this platform."
-      $ECHO "Please open an issue to request support for this distribution.${CLR_CLR}"
-      return 1
-    fi
+	if [ ! -f "$UNAME_PATH" ]; then
+	  print-fail "prompt: shell cannot be installed on this platform."
+	  print-warn "Please open an issue to request support for this distribution."
+	  return 1
+	fi
 
-    . "$UNAME_PATH"
+	. "$UNAME_PATH"
 
-    if ! grep "$PROMPT_SHELL_PATH" /etc/shells 1>/dev/null 2>&1; then
-        $ECHO "${CLR_SUCCESS}adding updated $PROMPT_SHELL to shells...${CLR_CLEAR}"
-        sudo sh -c "echo $PROMPT_SHELL_PATH >> /etc/shells"
-    fi
+	if ! grep "$PROMPT_SHELL_PATH" /etc/shells 1>/dev/null 2>&1; then
+		print-success "prompt: adding updated $PROMPT_SHELL to shells..."
+		sudo sh -c "printf \"%s\n\" $PROMPT_SHELL_PATH >> /etc/shells"
+	fi
 
-    if [ "$SHELL" != "$PROMPT_SHELL_PATH" ]; then
-        $ECHO "${CLR_SUCCESS}setting updated $PROMPT_SHELL to default shell for user...${CLR_CLEAR}"
-        sudo chsh -s $PROMPT_SHELL_PATH $(whoami)
+	if [ "$SHELL" != "$PROMPT_SHELL_PATH" ]; then
+		print-success "setting updated $PROMPT_SHELL to default shell for user..."
+		sudo chsh -s "$PROMPT_SHELL_PATH" "$(whoami)"
 
-        # set the default shell for the current session
-        export SHELL="$PROMPT_SHELL_PATH"
-    fi
+		# set the default shell for the current session
+		export SHELL="$PROMPT_SHELL_PATH"
+	fi
 
-    $ECHO "${CLR_SUCCESS}"
-    $ECHO "##############################################################################"
-    $ECHO "##############################################################################"
-    $ECHO "     NOTE: to take advantage of the symbols used by the shell, please set"
-    $ECHO "           the terminal font to 'FiraCode Nerd Font Mono'. If you are using"
-    $ECHO "           either macOS terminal or gnome terminal, you can do this"
-    $ECHO "           automatically by loading a \`theme\`."
-    $ECHO
-    $ECHO "     \$SHELL will be $SHELL"
-    $ECHO "     PLEASE RUN THE FOLLOWING TO START USING THE NEW SHELL:"
-    $ECHO
-    $ECHO "     exec \$SHELL -l"
-    $ECHO "##############################################################################"
-    $ECHO "##############################################################################"
-    $ECHO "${CLR_CLEAR}"
+	printf "\n\n%s" "${CLR_SUCCESS}"
+	cat <<-EOT
+		##############################################################################
+		##############################################################################
+
+		  NOTE: to take advantage of the symbols used by the shell, please set the
+		        the terminal font to \`FiraCode Nerd Font Mono\`. If you are using
+		        either macOS terminal or gnome terminal, you can do this automatically
+		        by loading a \`theme\`.
+
+		  \$SHELL will be $SHELL
+
+		  PLEASE RUN THE FOLLOWING TO START USING THE NEW SHELL:
+
+		  exec \$SHELL -l
+
+		##############################################################################
+		##############################################################################
+	EOT
+	printf "%s\n\n" "${FORMAT_CLEAR}"
 }
 
-__am_prompt_use_shell $@
+__am_prompt_use_shell "$@"
